### ISSUE TITLE
Can I connect webview with puppeteer?

### ISSUE THREAD

**Issue by baramofme** [shreyassanthu77/webview_dart#9]
Hello. I want use webview_dart with flutter pupetter.

https://pub.dev/packages/puppeteer

Can I controll webview_dart with puppeteer?

Thanks Regards

**Comment by shreyassanthu77** [comment]
TLDR; if you run this on newer versions of windows 10 or windows 11 it should work in debug mode

I guess so, It depends on the platform, if you have the chromium based edge then It should work if you start the webview in debug mode ( I haven't tested it but it should work as far as I can see. But it only works on windows because this library uses native browsers on Mac and Linux i.e. webkit and gtk respectively.

**Comment by baramofme** [comment]
@shreyassanthu77 Thanks reply! I hope it worked!

**Comment by shreyassanthu77** [comment]
.
